import expressAsyncHandler from "express-async-handler";
import { CardCollection } from "../models/cardCollection.model";
import { Card } from "../models/card.model";

export const getCardCollections = expressAsyncHandler(
  async (req: any, res: any) => {
    try {
      const userId = req.user.id;

      if (!userId) {
        res.status(500);
        throw new Error("Cannot read user.");
      }
      const collections = await CardCollection.find({ user_id: userId }).sort({
        updatedAt: -1,
      });
      res.status(200).json(collections);
    } catch (error: any) {
      res.status(500);
      throw new Error(error.message);
    }
  }
);

export const getCardCollection = expressAsyncHandler(
  async (req: any, res: any) => {
    try {
      const { id } = req.params;
      const cards = await Card.find({ collection_id: id as string });
      const collection = await CardCollection.findById(id);

      res.status(200).json({ ...collection, cards });
    } catch (error: any) {
      res.status(500);
      throw new Error(error.message);
    }
  }
);

export const postCardCollection = expressAsyncHandler(
  async (req: any, res: any) => {
    const userId = req.user.id;

    if (!userId) {
      res.status(500);
      throw new Error("Cannot read user.");
    }

    try {
      const collection = await CardCollection.create({
        user_id: userId,
        ...req.body,
      });

      // Generate and insert cards for the collection using the Card model
      const cards = [];
      for (let i = 1; i <= collection.number_of_cards; i++) {
        cards.push({
          card_number: i,
          collection_id: collection._id,
          user_id: userId,
          // Add other card properties as needed
        });
      }

      // Use the Card model to insert cards
      await Card.insertMany(cards);

      res.status(201).json({ message: `Collection successfully created!` });
    } catch (error: any) {
      res.status(500);
      throw new Error(error.message);
    }
  }
);

export const deleteCardCollection = expressAsyncHandler(
  async (req: any, res: any) => {
    try {
      const { id } = req.params;
      const collection = await CardCollection.findByIdAndDelete(id);
      if (!collection) {
        res.status(404);
        throw new Error(`Cannot find any collection with ID ${id}`);
      }

      // also delete all cards that collection_id is equal to id
      await Card.deleteMany({ collection_id: id });

      res.status(200).json("Collection deleted.");
    } catch (error: any) {
      res.status(500);
      throw new Error(error.message);
    }
  }
);

export const downloadCardCollection = expressAsyncHandler(
  async (req: any, res: any) => {
    try {
      const { id } = req.params;

      const cardCollection = await CardCollection.findById(id);
      if (!cardCollection) {
        res.status(500);
        throw new Error("Cannot find collection.");
      }
      const cards = await Card.find({ collection_id: id as string });

      const ownedCards = cards.filter((card) => card.owned);
      const missingCards = cards.filter((card) => !card.owned);
      const duplicates = cards.filter((card) => card.duplicates > 0);

      const fileContent =
        "Generated by MyStickers!\n\n" +
        `${cardCollection.name}\n\n` +
        `Owned Cards:\n${ownedCards
          .map((card: any) => card.card_number)
          .join(", ")}\n\n` +
        `Missing Cards:\n${missingCards
          .map((card) => card.card_number)
          .join(", ")}\n\n` +
        `Duplicate Cards:\n${duplicates
          .map((card: any) => `${card.card_number}(${card.duplicates})`)
          .join(", ")}`;

      // Set the response headers for downloading
      res.setHeader(
        "Content-Disposition",
        "attachment; filename=categorized-cards.txt"
      );
      res.setHeader("Content-Type", "text/plain");
      // Send the text file content as the response

      res.send(fileContent);
    } catch (error: any) {
      res.status(500);
      console.log("here? errror 500");
      throw new Error("Error fetching the cards.");
    }
  }
);
